global using Microsoft.AspNetCore.Authorization;
global using Microsoft.AspNetCore.Builder;
global using Microsoft.AspNetCore.Http;
global using Microsoft.AspNetCore.Mvc;
global using Microsoft.AspNetCore.Routing;
global using StubGPT.Core;
global using System.Net;
global using Microsoft.Extensions.DependencyInjection;
global using StubGPT.Database;
